export const talents=[{name:'物理直觉',desc:'力学初始 +12，学习收益 +15%',key:'intuition'},{name:'实验巧手',desc:'实验初始 +18',key:'hands'},{name:'稳如磐石',desc:'心态初始 +15，比赛发挥更稳定',key:'calm'},{name:'数学底子',desc:'电磁学初始 +12',key:'math'},{name:'自律达人',desc:'每周拥有 7 个行动点',key:'discipline'},{name:'乐天派',desc:'每周额外恢复 5 点心态',key:'optimist'}];
export const actions=[{id:'mechanics',icon:'↗',name:'力学专题',desc:'从受力分析到刚体运动，建立物理直觉。',cost:2,gain:{mechanics:9,mood:-5},hint:'力学 +9 · 心态 −5'},{id:'electro',icon:'ϟ',name:'电磁学研习',desc:'画好每一条场线，推导每一个边界条件。',cost:2,gain:{electro:9,mood:-5},hint:'电磁学 +9 · 心态 −5'},{id:'thermal',icon:'☼',name:'热学与光学',desc:'在微观世界与光的波动之间寻找答案。',cost:2,gain:{thermal:9,mood:-4},hint:'热光 +9 · 心态 −4'},{id:'lab',icon:'⚗',name:'实验室训练',desc:'调平、读数、拟合，让数据说话。',cost:2,gain:{lab:10,mood:-3},hint:'实验 +10 · 心态 −3'},{id:'school',icon:'▤',name:'回归文化课',desc:'补上落下的作业，给未来留一条路。',cost:1,gain:{school:6,mood:-1},hint:'文化课 +6 · 心态 −1'},{id:'rest',icon:'♧',name:'去操场走走',desc:'放下笔。晚风和朋友也是青春的一部分。',cost:1,gain:{mood:12,school:1},hint:'心态 +12 · 文化课 +1'}];
export const events=[{title:'第一道解不出的题',text:'晚自习结束了，黑板上的圆环还在转动。你算了三页纸，答案却始终多一个负号。同桌收拾好书包，问你要不要一起去问教练。',choices:[{name:'带着草稿去请教',result:'教练没有给答案，只问：“你选的参考系是什么？”你忽然看到了问题的入口。',gain:{mechanics:5,mood:2}},{name:'再独立想一会儿',result:'你重新画图，终于发现约束条件。走出教室时，走廊已经熄灯。',gain:{mechanics:7,mood:-5}}]},{title:'一封来自家里的消息',text:'手机亮了。妈妈问：“最近睡得好吗？不一定每次都要赢。”桌上的习题集摊开着，旁边是还没吃的晚饭。',choices:[{name:'打个电话，聊聊近况',result:'你们没有谈分数。挂电话后，晚饭还是温的。',gain:{mood:10}},{name:'先把这一题做完',result:'你发了一个“放心”，又低下头。今晚的推导格外顺利。',gain:{electro:5,mood:-3}}]},{title:'实验台上的意外',text:'同组同学得到了一条漂亮的直线，你的散点却乱得像星空。距离实验室关门还有二十分钟。',choices:[{name:'重新检查仪器零点',result:'原来是游标卡尺的零点误差。你学会了先相信记录，再质疑仪器。',gain:{lab:7}},{name:'和同学一起讨论数据',result:'你们比较了测量步骤，发现固定装置松动了。合作有时比独自坚持更有效。',gain:{lab:4,mood:5}}]},{title:'排名表背后的名字',text:'模拟考排名贴在门口。那个总和你讨论题目的朋友，这次排在你前面。你看着分数，心里有一点酸。',choices:[{name:'约他交换错题',result:'他的解法和你完全不同。你们在同一张纸上，画出了两条抵达答案的路。',gain:{thermal:5,mood:4}},{name:'把目标写在笔记本上',result:'你把不甘心变成了计划，也提醒自己：对手并不是敌人。',gain:{mechanics:5,mood:-2}}]}];
events.push(
{title:'窗边的月亮',text:'光学题里出现了望远镜。你抬头看见窗外的月亮，忽然想起：最初喜欢物理，并不是为了排名。',choices:[{name:'用透镜搭一个小望远镜',result:'成像很模糊，但月亮真的近了一点。课本里的公式，第一次变成手心里的世界。',gain:{thermal:6,lab:3}},{name:'放下试卷，看看夜空',result:'你记不起月面的名字，却记得今晚的风。明天还有题目，今晚先留给自己。',gain:{mood:10}}]},
{title:'教练的空白批注',text:'教练把模拟卷还给你，最后一道题没有打叉，只写着：“先说明你的模型。”你突然发现，算式写满了，假设却一句也没有。',choices:[{name:'重新写出每一步假设',result:'你区分了理想化、近似和结论。物理不只是计算，也是在解释计算为什么成立。',gain:{mechanics:6,electro:3}},{name:'请教练示范一次解题',result:'教练从一张图开始，用十分钟替代了三页代数。你决定先养成画图的习惯。',gain:{mechanics:4,mood:4}}]},
{title:'文化课的小测',text:'英语老师把你叫到走廊：“竞赛很重要，但这张卷子也要认真看看。”教室里正在讨论下一次集训，而你的错题本已经很久没翻开。',choices:[{name:'今晚补齐文化课笔记',result:'你用一晚把漏洞标了出来。没有立刻追上所有人，但至少知道了从哪里开始。',gain:{school:10,mood:-3}},{name:'和老师约一个补课计划',result:'老师帮你把任务拆成了几小块。路不止一条，你也不必同时走完所有路。',gain:{school:5,mood:5}}]},
{title:'离开教室的同伴',text:'一起上过第一堂竞赛课的同学决定回归文化课。收拾书包时，他把一叠实验记录递给你：“替我再往前看看。”',choices:[{name:'认真收下，约好保持联系',result:'你们约定周末一起吃饭。方向变了，友谊并没有被成绩表带走。',gain:{lab:4,mood:6}},{name:'送他一本写满批注的笔记',result:'你把扉页留白，说以后还可以一起讨论有趣的问题。物理教室外，也有很大的世界。',gain:{school:4,mood:7}}]}
);

const clamp=x=>Math.max(0,Math.min(100,x));
export function createGame(name,selected){return {version:1,name:name.trim().slice(0,16)||'物竞少年',talents:selected,week:1,stats:{mechanics:18+(selected.includes('intuition')?12:0),electro:15+(selected.includes('math')?12:0),thermal:15,lab:10+(selected.includes('hands')?18:0),school:65,mood:70+(selected.includes('calm')?15:0)},log:[],medals:[],route:true,pending:null,ended:false};}
export function applyGain(state,gain,learning=false){for(const [key,value]of Object.entries(gain)){state.stats[key]=clamp(state.stats[key]+(learning&&value>0&&['mechanics','electro','thermal','lab'].includes(key)&&state.talents.includes('intuition')?Math.round(value*1.15):value));}}
export function budget(state){return state.talents.includes('discipline')?7:6;}
export function exam(state,random=Math.random){const s=state.stats;const base=(s.mechanics+s.electro+s.thermal)/3*.72+s.lab*.28;const score=Math.round(clamp(base*(.75+s.mood/400)+(random()-.5)*(state.talents.includes('calm')?8:18)));const stage=state.week===8?'预赛':state.week===16?'复赛':'全国决赛';const threshold=state.week===8?35:state.week===16?62:82;const pass=score>=threshold;state.medals.push({stage,score,pass,title:state.week===24?(pass?'国赛金牌':score>=70?'国赛银牌':'国赛铜牌'):(pass?(state.week===8?'晋级复赛':'入选省队'):'未能晋级')});if(!pass&&state.week!==24)state.route=false;return state.medals.at(-1);}
export function advance(state,plan,random=Math.random){if(state.ended||state.pending)throw Error('当前无法推进');const cost=plan.reduce((sum,id)=>{const action=actions.find(a=>a.id===id);if(!action)throw Error('未知行动');return sum+action.cost;},0);if(!plan.length||cost>budget(state))throw Error('行动点不足或计划为空');for(const id of plan)applyGain(state,actions.find(a=>a.id===id).gain,true);applyGain(state,{school:-3,mood:state.talents.includes('optimist')?5:-2});state.log.unshift({week:state.week,text:plan.map(id=>actions.find(a=>a.id===id).name).join('、')});let result=null;if([8,16,24].includes(state.week)&&state.route){result=exam(state,random);state.log.unshift({week:state.week,text:`${result.stage}：${result.score} 分，${result.title}。`});}if(state.week===24){state.ended=true;return result;}state.week++;if(state.week%3===0)state.pending=events[Math.floor(random()*events.length)];return result;}
export function choose(state,index){const choice=state.pending?.choices[index];if(!choice)throw Error('无效选择');applyGain(state,choice.gain);state.log.unshift({week:state.week,text:choice.result});state.pending=null;}
export function ending(state){const last=state.medals.at(-1);if(last?.stage==='全国决赛')return last.title==='国赛金牌'?'追光的人': '山顶的风景';if(state.stats.school>=80)return '另一条闪光的路';if(state.stats.mood>=65)return '热爱不止于奖牌';return '青春的未完成式';}
