import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createGame,actions,effectiveGain,performAction,advance,choose,randomEvent,createEventPlan,canChoose,dailyEvent,physicalKeys,romanceRecovery} from '../game.js';
import {createCalibratedGame} from '../calibration.js';import {validSave} from '../storage.js';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/event-parameters.json',import.meta.url)));
const make=ids=>createGame('参数测试',ids||['grinder','lost'],()=>.9,null,{balanceVersion:2,attributeRulesVersion:1});
function catalog(s){const found=new Map();for(const relationship of [false,true])for(let i=0;i<1000;i++){const e=randomEvent({...s,relationship,relationshipSince:-3},()=>i/1000);found.set(e.id,e);}const special=randomEvent({...s,talents:['grinder','lost','jiahao']},()=>0);found.set(special.id,special);return found;}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
test('18类事件及36个选项逐项符合用户Word表格的数值和名称',()=>{const pool=catalog(make());assert.equal(pool.size,18);for(const expected of fixture){const e=pool.get(expected.id);assert.ok(e,expected.id);assert.deepEqual(e.choices.map(c=>({name:c.name,gain:c.gain})),expected.choices,expected.id);}});
test('全部行动正收益减半，负收益不变，包含休息；事件不再次减半',()=>{const s=make();for(const a of actions){const gain=effectiveGain(s,a.gain,true);for(const [k,v]of Object.entries(a.gain))near(gain[k],v>0?v/2:v);}assert.deepEqual(effectiveGain(s,{mechanics:2,mood:2}),{mechanics:2,mood:2});s.stats.mood=50;performAction(s,'rest',()=>.9);assert.equal(s.stats.mood,51);near(s.stats.school,65+1/6);});
test('正收益减半在精神错乱随机偏移之后按符号应用，并与判定倍率叠加',()=>{const s=make(['grinder','chaos']);assert.deepEqual(effectiveGain(s,{mechanics:3,mood:-5},true,()=>.999),{mechanics:3,mood:-2});assert.deepEqual(effectiveGain(s,{mechanics:3},true,()=>0),{mechanics:-2});const t=make();t.stats.mood=80;performAction(t,'mechanics',()=>0);assert.equal(t.stats.mechanics,21);assert.equal(t.stats.mood,77.5);});
test('难题门槛为round(22+1.2d)，学科奖励2，存活日程与替代故事同一参数',()=>{const s=make();for(const day of [1,8,12,24,36,48]){s.week=day;const e=catalog(s).get('challenge-modern');assert.equal(e.choices[0].requires.modern,Math.round(22+day*1.2));assert.equal(e.choices[0].gain.modern,2);}s.week=1;const plan=createEventPlan(s,42);for(const slot of plan){if(slot.fallback.id==='fallback-story-0')assert.deepEqual(slot.fallback.choices[0].gain,{mechanics:2,mood:2});}});
test('约会心态10、七项学习能力各减1；失恋门槛50且结束关系、恢复行动点',()=>{const s=make();const pool=catalog(s);const academic=[...physicalKeys,'school'];const date=pool.get('romance-date');assert.equal(date.choices[0].gain.mood,10);for(const k of academic)assert.equal(date.choices[0].gain[k],-1);const e=pool.get('romance-breakup');assert.equal(e.choices[0].gain.mood,-10);s.relationship=true;s.relationshipSince=-3;s.pending=e;s.stats.mood=49;assert.equal(canChoose(s,e.choices[1]),false);assert.throws(()=>choose(s,1));s.stats.mood=50;choose(s,1,()=>.9);assert.equal(s.stats.mood,45);assert.equal(s.relationship,false);assert.equal(s.romanceCooldown,4);for(const k of academic)assert.equal(e.choices[1].gain[k],1);});
test('恋爱日常回复3，且不被常规行动减半；旧局规则保持原值',()=>{const s=make();s.relationship=true;s.stats.mood=50;s.stats.school=50;advance(s,['rest'],()=>.9);assert.equal(s.stats.mood,57);assert.equal(romanceRecovery(s),3);const old=createGame('旧局',['grinder','lost'],()=>.9);assert.equal(romanceRecovery(old),2);assert.equal(effectiveGain(old,actions[0].gain,true).mechanics,3);assert.equal(catalog(old).get('romance-breakup').choices[1].name,'独自整理回忆');});
test('新局与10000次校准记录同一参数版本，36与48回合都完成校准并可存档',()=>{for(const headstart of [false,true]){const s=createCalibratedGame({name:'测试',talents:['grinder','lost',...(headstart?['headstart']:[])],identity:'ordinary',seed:42});assert.equal(s.balanceVersion,2);assert.equal(s.calibration.balanceVersion,2);assert.ok(s.calibration.years.every(y=>y.actualFinalExams>0));assert.ok(validSave(s));const bad=JSON.parse(JSON.stringify(s));delete bad.calibration.balanceVersion;assert.equal(validSave(bad),false);}});
