import {test} from 'node:test';import assert from 'node:assert/strict';
import {createCalibratedGame,calibrateRun,calibrationSettings} from '../calibration.js';
import {createGame,dailyEvent,examThreshold,awardThreshold,createEventPlan} from '../game.js';
import {validSave,migrateSave} from '../storage.js';
const config={name:'陈梓涵',talents:['grinder','lost'],identity:'ordinary',seed:42};
test('每场真实运行10000人，九场独立校准；同种子可复现且跨局完整赛程分数线不同',()=>{const a=createCalibratedGame(config),b=createCalibratedGame(config),c=createCalibratedGame({...config,seed:43});assert.equal(a.calibration.sampleSize,10000);assert.equal(a.calibration.competitionCount,9);assert.equal(a.calibration.totalSimulations,90000);assert.deepEqual(a.calibration.initialLearningRounds,{初三:0,高一:12,高二:24});assert.deepEqual(a,b);assert.notDeepEqual(a.eventPlan,c.eventPlan);assert.notDeepEqual(a.yearCutoffs,c.yearCutoffs);assert.ok(a.calibration.actualFinalExams>0);assert.equal(examThreshold(a,8),a.runCutoffs.preliminary);assert.equal(awardThreshold(a,'silver'),a.runCutoffs.silver);});
test('玩家与无天赋模拟共享同一天的内容和能力门槛，不消耗各自随机流',()=>{const player=createCalibratedGame(config);const sim=createGame('模拟',['grinder','lost'],()=>.9);sim.talents=[];sim.eventPlan=player.eventPlan;for(let day=1;day<=24;day++){player.week=sim.week=day;assert.deepEqual(dailyEvent(player,()=>0),dailyEvent(sim,()=>.999));}const before=JSON.stringify(player.eventPlan);const e=dailyEvent(player);e.choices[0].gain.mood=999;assert.equal(JSON.stringify(player.eventPlan),before);});
test('关系不满足时统一替代，同样关系状态下相同事件',()=>{const player=createCalibratedGame({...config,seed:1});const slot=player.eventPlan.find(s=>s.condition==='single');assert.ok(slot);player.week=slot.primary.day;player.relationship=true;const other=JSON.parse(JSON.stringify(player));assert.deepEqual(dailyEvent(player),slot.fallback);assert.deepEqual(dailyEvent(player),dailyEvent(other));player.relationship=false;assert.deepEqual(dailyEvent(player),slot.primary);});
test('准备期与专属事件均纳入共享日程，续存不再校准',()=>{const player=createGame('测试',['grinder','lost','headstart','jiahao'],()=>.9,'prodigy');player.worldSeed=42;player.eventPlan=createEventPlan(player,42);assert.equal(player.eventPlan.length,36);assert.ok(player.eventPlan.some(s=>s.primary.id==='jiahao-special'));player.calibration=calibrateRun(player);player.runCutoffs=player.calibration.cutoffs;const restored=migrateSave(JSON.parse(JSON.stringify(player)));assert.ok(validSave(restored));assert.deepEqual(restored.runCutoffs,player.runCutoffs);assert.deepEqual(restored.eventPlan,player.eventPlan);});
test('缺少本局日程、无效阈值或破损校准包的存档不加载',()=>{const s=createCalibratedGame(config);assert.ok(validSave(s));for(const mutate of [t=>delete t.eventPlan,t=>t.eventPlan[0].primary.choices[0].gain.unknown=2,t=>t.runCutoffs.gold=-1,t=>t.calibration.sampleSize=999,t=>t.calibration.qualificationRatio=.2,t=>delete t.calibration.cutoffRulesVersion,t=>t.calibration.years[0].sampleSize=1000]){const t=JSON.parse(JSON.stringify(s));mutate(t);assert.ok(!validSave(t));}});

test('每场预赛前10%进入复赛、复赛前10%进入决赛，普通及提前准备局均适用',()=>{for(const headstart of [false,true]){const s=createCalibratedGame({...config,talents:['grinder','lost',...(headstart?['headstart','jiahao']:[])]});for(const year of s.calibration.years){assert.equal(year.semifinalists,Math.ceil(year.actualPreExams*.1));assert.equal(year.finalists,Math.ceil(year.actualSemiExams*.1));assert.ok(year.actualFinalExams>0);assert.ok(year.cutoffs.training>=year.cutoffs.gold&&year.cutoffs.gold>=year.cutoffs.silver);assert.notEqual(year.semifinalists,Math.ceil(year.actualPreExams*.3));}assert.ok(validSave(s));}});

test('旧年级存档保留1000人校准，新存档人数和规则版本必须一致',()=>{
 const s=createGame(config.name,config.talents,()=>.9,config.identity,{calendarVersion:3,attributeRulesVersion:1,balanceVersion:2,jiahaoVersion:1});
 s.worldSeed=42;s.eventPlan=createEventPlan(s,42);s.calibration=calibrateRun(s);s.runCutoffs=s.calibration.cutoffs;s.yearCutoffs=s.calibration.years.map(y=>y.cutoffs);
 assert.deepEqual(calibrationSettings(s),{sampleSize:1000,qualificationRatio:.2});assert.ok(validSave(s));assert.equal(s.calibration.sampleSize,1000);
 const changed=JSON.parse(JSON.stringify(s));changed.cutoffRulesVersion=2;assert.ok(!validSave(changed));
 assert.deepEqual(calibrationSettings(changed),{sampleSize:10000,qualificationRatio:.1});
});
