import {writeFile} from 'node:fs/promises';
import {createGame,advance,choose,budget,actions,canChoose,competitionDay} from '../game.js';
import {identities} from '../identities.js';
// 固定种子使每次校准可复现。排序均为从高到低；按名次取前X%的边界。
let seed=20261008;
const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const runs=Array.from({length:1000},(_,id)=>{
 const identity=identities[Math.floor(random()*identities.length)].key;
 const s=createGame('模拟',['grinder','lost'],()=>.9,identity);
 s.talents=[];s.dailyPenalty=0;s.log=[];
 return {id,state:s,pre:null,semi:null,final:null};
});
function simulate(run,target){
 const s=run.state;
 while(!s.ended&&competitionDay(s)<=target){
  s.route=true;
  const plan=[];let remaining=1+Math.floor(random()*budget(s));
  while(remaining>0){const available=actions.filter(a=>a.cost<=remaining);const action=available[Math.floor(random()*available.length)];plan.push(action.id);remaining-=action.cost;}
  advance(s,plan,random);
  if(s.pending){const available=s.pending.choices.map((c,i)=>canChoose(s,c)?i:null).filter(i=>i!==null);choose(s,available[Math.floor(random()*available.length)],random);}
 }
 const stage=target===8?'预赛':target===16?'复赛':'全国决赛';
 return s.medals.find(m=>m.stage===stage)?.score??null;
}
const eligible=(list,field)=>list.filter(r=>r[field]!==null);
const top=(list,field,ratio)=>{const candidates=eligible(list,field);return candidates.sort((a,b)=>b[field]-a[field]||a.id-b.id).slice(0,Math.ceil(candidates.length*ratio));};
for(const r of runs)r.pre=simulate(r,8);
const semifinalists=top(runs,'pre',.3);
for(const r of semifinalists)r.semi=simulate(r,16);
const finalists=top(semifinalists,'semi',.3);
for(const r of finalists)r.final=simulate(r,24);
const threshold=(list,field,ratio)=>top(list,field,ratio).at(-1)?.[field]??null;
const cutoffs={preliminary:threshold(runs,'pre',.3),semifinal:threshold(semifinalists,'semi',.3),training:threshold(finalists,'final',.1),gold:threshold(finalists,'final',.3),silver:threshold(finalists,'final',.7)};
const report={seed:20261008,sampleSize:1000,semifinalists:semifinalists.length,finalists:finalists.length,actualPreExams:runs.filter(r=>r.state.medals.some(m=>m.stage==='预赛')).length,actualSemiExams:semifinalists.filter(r=>r.state.medals.some(m=>m.stage==='复赛')).length,actualFinalExams:finalists.filter(r=>r.state.medals.some(m=>m.stage==='全国决赛')).length,ranking:'descending; gameover before an exam excluded; top-percent cutoff inclusive',dailyPlan:'uniform random action-point allowance from 1 to budget; random affordable actions',cutoffs};
if(Object.values(cutoffs).some(v=>v===null))throw Error('No candidates for a required competition threshold');
await writeFile(new URL('../cutoffs.js',import.meta.url),'// Generated by npm run calibrate. Internal calibration; not rendered in game UI.\nexport const cutoffs='+JSON.stringify(cutoffs)+';\n');
await writeFile(new URL('../calibration-report.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
